#!/usr/bin/with-contenv sh

# Wait for SQL.
while ! mysqladmin ping -hmysql --silent; do
    sleep 1
done

/usr/local/bin/confd -onetime -backend env

if [ $FEDORA_RESOURCE_INDEX = "blazegraph" ]; then
   mv /usr/local/fedora/server/config/spring/remote-blazegraph.bk /usr/local/fedora/server/config/spring/remote-blazegraph.xml
fi